// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "help.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(436, 523);
    w = o;
    o->box(FL_PLASTIC_THIN_DOWN_BOX);
    new Fl_Help_View(15, 15, 410, 460);
    { Fl_Button* o = new Fl_Button(330, 485, 89, 25, "Close");
      o->align(FL_ALIGN_TOP);
    }
    o->end();
  }
  return w;
}
