// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef help_h
#define help_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Help_View.H>
#include <FL/Fl_Button.H>
Fl_Double_Window* make_window();
#endif
