// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef PsiSeer_h
#define PsiSeer_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern void callback(Fl_Double_Window*, void*);
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Light_Button.H>
Fl_Double_Window* make_window();
#endif
